services:
  - type: web
    name: order-qrcode-system
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app --bind 0.0.0.0:$PORT
    envVars:
      - key: FLASK_ENV
        value: production
      - key: PYTHONPATH
        value: /opt/render/project/src
    disk:
      name: qr-data
      mountPath: /opt/render/project/src/data
      sizeGB: 1 